[package]
name = "rust"
version = "0.1.0"
authors = ["Damien Joris <damien.joris@promyze.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "1.1.0"